export const SUBSCRIPTION_CREATE_REQUEST = 'SUBSCRIPTION_CREATE_REQUEST'
export const SUBSCRIPTION_CREATE_SUCCESS = 'SUBSCRIPTION_CREATE_SUCCESS'
export const SUBSCRIPTION_CREATE_FAIL = 'SUBSCRIPTION_CREATE_FAIL'
export const SUBSCRIPTION_CREATE_RESET = 'SUBSCRIPTION_CREATE_RESET'

export const SUBSCRIPTION_DETAILS_REQUEST = 'SUBSCRIPTION_DETAILS_REQUEST'
export const SUBSCRIPTION_DETAILS_SUCCESS = 'SUBSCRIPTION_DETAILS_SUCCESS'
export const SUBSCRIPTION_DETAILS_FAIL = 'SUBSCRIPTION_DETAILS_FAIL'

export const SUBSCRIPTION_LIST_MY_REQUEST = 'SUBSCRIPTION_LIST_MY_REQUEST'
export const SUBSCRIPTION_LIST_MY_SUCCESS = 'SUBSCRIPTION_LIST_MY_SUCCESS'
export const SUBSCRIPTION_LIST_MY_FAIL = 'SUBSCRIPTION_LIST_MY_FAIL'
export const SUBSCRIPTION_LIST_MY_RESET = 'SUBSCRIPTION_LIST_MY_RESET'

export const SUBSCRIPTION_LIST_REQUEST = 'SUBSCRIPTION_LIST_REQUEST'
export const SUBSCRIPTION_LIST_SUCCESS = 'SUBSCRIPTION_LIST_SUCCESS'
export const SUBSCRIPTION_LIST_FAIL = 'SUBSCRIPTION_LIST_FAIL'
